block_builder:
    block:
        max_block_bytes: 1.048576e+08
        blockpack:
            vector_dimension: 384
    consume_cycle_duration: 3m
    partitions_per_instance: 1
distributor: {}
http_api_prefix: /tempo
ingest:
    enabled: true
    kafka:
        address: warpstream-agent-read.tempo-dev-test-03.svc.cluster.local.:9092
        client_id: warpstream_partition_assignment_strategy=equal_spread,warpstream_proxy_target=proxy-consume
        sasl_password: ccp_tempo_dev_test_03
        sasl_username: ccun_tempo_dev_test_03
        topic: ingest
memberlist:
    abort_if_cluster_join_fails: false
    bind_port: 7946
    cluster_label: dev-us-east-0.tempo-dev-test-03
    join_members:
        - dns+gossip-ring.tempo-dev-test-03.svc.cluster.local.:7946
memory:
    automemlimit_enabled: true
multitenancy_enabled: true
overrides:
    ingestion_burst_size_bytes: 2e+07
    ingestion_rate_limit_bytes: 500000
    ingestion_rate_strategy: global
    metrics_generator_native_histogram_max_bucket_number: 60
    per_tenant_override_config: /overrides/overrides.yaml
partition_ring_live_store: true
server:
    grpc_server_max_recv_msg_size: 1.572864e+07
    grpc_server_max_send_msg_size: 1.572864e+07
    http_listen_port: 3100
    log_level: info
storage:
    trace:
        azure:
            container_name: dev-us-east-0-tempo-dev-test-03
        backend: s3
        block:
            blockpack:
                vector_dimension: 384
            version: vblockpack
        blocklist_poll: "0"
        blocklist_poll_tenant_concurrency: 1
        blocklist_poll_tenant_index_builders: 1
        cache: ""
        empty_tenant_deletion_age: 24h
        empty_tenant_deletion_enabled: true
        gcs:
            bucket_name: dev-us-east-0-tempo-dev-test-03
            chunk_buffer_size: 1.048576e+07
        memcached: {}
        pool:
            queue_depth: 2000
        s3:
            bucket: dev-us-east-0-tempo-dev-test-03
            endpoint: s3.dualstack.us-east-2.amazonaws.com
        wal:
            path: /var/tempo/wal
