FROM docker.redpanda.com/redpandadata/redpanda:latest

EXPOSE 9092 8081 8082 9644

CMD ["redpanda", "start", \
    "--kafka-addr", "internal://0.0.0.0:9092,external://0.0.0.0:19092", \
    "--advertise-kafka-addr", "internal://redpanda:9092,external://localhost:19092", \
    "--pandaproxy-addr", "internal://0.0.0.0:8082,external://0.0.0.0:18082", \
    "--advertise-pandaproxy-addr", "internal://redpanda:8082,external://localhost:18082", \
    "--schema-registry-addr", "internal://0.0.0.0:8081,external://0.0.0.0:18081", \
    "--rpc-addr", "redpanda:33145", \
    "--advertise-rpc-addr", "redpanda:33145", \
    "--mode", "dev-container", \
    "--smp", "1", \
    "--default-log-level=info"]