// Code generated by goyacc -o expr.y.go -p yy expr.y. DO NOT EDIT.

//line expr.y:2
package traceql

import __yyfmt__ "fmt"

//line expr.y:2

import (
	"math"
	"time"
)

//line expr.y:12
type yySymType struct {
	yys               int
	root              RootExpr
	groupOperation    GroupOperation
	coalesceOperation CoalesceOperation
	selectOperation   SelectOperation
	attributeList     []Attribute

	spansetExpression         SpansetExpression
	spansetPipelineExpression SpansetExpression
	wrappedSpansetPipeline    Pipeline
	spansetPipeline           Pipeline
	spansetFilter             *SpansetFilter
	scalarFilter              ScalarFilter
	scalarFilterOperation     Operator

	scalarPipelineExpressionFilter ScalarFilter
	scalarPipelineExpression       ScalarExpression
	scalarExpression               ScalarExpression
	wrappedScalarPipeline          Pipeline
	scalarPipeline                 Pipeline
	aggregate                      Aggregate
	metricsAggregation             firstStageElement
	metricsSecondStage             secondStageElement

	fieldExpression      FieldExpression
	static               Static
	intrinsicField       Attribute
	attributeField       Attribute
	attribute            Attribute
	scopedIntrinsicField Attribute

	binOp          Operator
	staticInt      int
	staticStr      string
	staticFloat    float64
	staticDuration time.Duration
	numericList    []float64

	hint     *Hint
	hintList []*Hint
	hints    *Hints
}

const IDENTIFIER = 57346
const STRING = 57347
const INTEGER = 57348
const FLOAT = 57349
const DURATION = 57350
const DOT = 57351
const OPEN_BRACE = 57352
const CLOSE_BRACE = 57353
const OPEN_PARENS = 57354
const CLOSE_PARENS = 57355
const COMMA = 57356
const NIL = 57357
const TRUE = 57358
const FALSE = 57359
const STATUS_ERROR = 57360
const STATUS_OK = 57361
const STATUS_UNSET = 57362
const KIND_UNSPECIFIED = 57363
const KIND_INTERNAL = 57364
const KIND_SERVER = 57365
const KIND_CLIENT = 57366
const KIND_PRODUCER = 57367
const KIND_CONSUMER = 57368
const IDURATION = 57369
const CHILDCOUNT = 57370
const NAME = 57371
const STATUS = 57372
const STATUS_MESSAGE = 57373
const PARENT = 57374
const KIND = 57375
const ROOTNAME = 57376
const ROOTSERVICENAME = 57377
const ROOTSERVICE = 57378
const TRACEDURATION = 57379
const NESTEDSETLEFT = 57380
const NESTEDSETRIGHT = 57381
const NESTEDSETPARENT = 57382
const ID = 57383
const TRACE_ID = 57384
const SPAN_ID = 57385
const PARENT_ID = 57386
const TIMESINCESTART = 57387
const VERSION = 57388
const PARENT_DOT = 57389
const RESOURCE_DOT = 57390
const SPAN_DOT = 57391
const TRACE_COLON = 57392
const SPAN_COLON = 57393
const EVENT_COLON = 57394
const EVENT_DOT = 57395
const LINK_COLON = 57396
const LINK_DOT = 57397
const INSTRUMENTATION_COLON = 57398
const INSTRUMENTATION_DOT = 57399
const COUNT = 57400
const AVG = 57401
const MAX = 57402
const MIN = 57403
const SUM = 57404
const BY = 57405
const COALESCE = 57406
const SELECT = 57407
const END_ATTRIBUTE = 57408
const RATE = 57409
const COUNT_OVER_TIME = 57410
const MIN_OVER_TIME = 57411
const MAX_OVER_TIME = 57412
const AVG_OVER_TIME = 57413
const SUM_OVER_TIME = 57414
const QUANTILE_OVER_TIME = 57415
const HISTOGRAM_OVER_TIME = 57416
const COMPARE = 57417
const TOPK = 57418
const BOTTOMK = 57419
const WITH = 57420
const VECTOR_AI = 57421
const VECTOR_ALL = 57422
const PIPE = 57423
const AND = 57424
const OR = 57425
const EQ = 57426
const NEQ = 57427
const LT = 57428
const LTE = 57429
const GT = 57430
const GTE = 57431
const NRE = 57432
const RE = 57433
const DESC = 57434
const ANCE = 57435
const SIBL = 57436
const NOT_CHILD = 57437
const NOT_PARENT = 57438
const NOT_DESC = 57439
const NOT_ANCE = 57440
const UNION_CHILD = 57441
const UNION_PARENT = 57442
const UNION_DESC = 57443
const UNION_ANCE = 57444
const UNION_SIBL = 57445
const ADD = 57446
const SUB = 57447
const NOT = 57448
const MUL = 57449
const DIV = 57450
const MOD = 57451
const POW = 57452

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENTIFIER",
	"STRING",
	"INTEGER",
	"FLOAT",
	"DURATION",
	"DOT",
	"OPEN_BRACE",
	"CLOSE_BRACE",
	"OPEN_PARENS",
	"CLOSE_PARENS",
	"COMMA",
	"NIL",
	"TRUE",
	"FALSE",
	"STATUS_ERROR",
	"STATUS_OK",
	"STATUS_UNSET",
	"KIND_UNSPECIFIED",
	"KIND_INTERNAL",
	"KIND_SERVER",
	"KIND_CLIENT",
	"KIND_PRODUCER",
	"KIND_CONSUMER",
	"IDURATION",
	"CHILDCOUNT",
	"NAME",
	"STATUS",
	"STATUS_MESSAGE",
	"PARENT",
	"KIND",
	"ROOTNAME",
	"ROOTSERVICENAME",
	"ROOTSERVICE",
	"TRACEDURATION",
	"NESTEDSETLEFT",
	"NESTEDSETRIGHT",
	"NESTEDSETPARENT",
	"ID",
	"TRACE_ID",
	"SPAN_ID",
	"PARENT_ID",
	"TIMESINCESTART",
	"VERSION",
	"PARENT_DOT",
	"RESOURCE_DOT",
	"SPAN_DOT",
	"TRACE_COLON",
	"SPAN_COLON",
	"EVENT_COLON",
	"EVENT_DOT",
	"LINK_COLON",
	"LINK_DOT",
	"INSTRUMENTATION_COLON",
	"INSTRUMENTATION_DOT",
	"COUNT",
	"AVG",
	"MAX",
	"MIN",
	"SUM",
	"BY",
	"COALESCE",
	"SELECT",
	"END_ATTRIBUTE",
	"RATE",
	"COUNT_OVER_TIME",
	"MIN_OVER_TIME",
	"MAX_OVER_TIME",
	"AVG_OVER_TIME",
	"SUM_OVER_TIME",
	"QUANTILE_OVER_TIME",
	"HISTOGRAM_OVER_TIME",
	"COMPARE",
	"TOPK",
	"BOTTOMK",
	"WITH",
	"VECTOR_AI",
	"VECTOR_ALL",
	"PIPE",
	"AND",
	"OR",
	"EQ",
	"NEQ",
	"LT",
	"LTE",
	"GT",
	"GTE",
	"NRE",
	"RE",
	"DESC",
	"ANCE",
	"SIBL",
	"NOT_CHILD",
	"NOT_PARENT",
	"NOT_DESC",
	"NOT_ANCE",
	"UNION_CHILD",
	"UNION_PARENT",
	"UNION_DESC",
	"UNION_ANCE",
	"UNION_SIBL",
	"ADD",
	"SUB",
	"NOT",
	"MUL",
	"DIV",
	"MOD",
	"POW",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 311,
	13, 87,
	-2, 95,
}

const yyPrivate = 57344

const yyLast = 1305

var yyAct = [...]int16{
	102, 6, 5, 8, 7, 99, 18, 101, 294, 251,
	12, 90, 67, 240, 241, 242, 251, 77, 233, 232,
	357, 13, 209, 296, 94, 30, 100, 309, 2, 256,
	255, 70, 156, 155, 159, 157, 208, 66, 238, 239,
	29, 240, 241, 242, 251, 87, 88, 89, 90, 208,
	376, 189, 191, 192, 193, 194, 195, 196, 197, 198,
	199, 200, 201, 202, 203, 204, 205, 206, 74, 75,
	76, 77, 19, 20, 21, 375, 17, 215, 169, 85,
	86, 350, 87, 88, 89, 90, 349, 354, 359, 360,
	19, 20, 21, 236, 17, 348, 169, 345, 344, 343,
	235, 342, 425, 213, 371, 402, 223, 225, 226, 227,
	228, 229, 230, 398, 397, 396, 231, 209, 395, 234,
	254, 382, 257, 258, 23, 26, 24, 25, 27, 14,
	170, 15, 353, 160, 161, 162, 163, 165, 164, 166,
	167, 168, 23, 26, 24, 25, 27, 14, 170, 15,
	381, 286, 434, 282, 284, 285, 252, 253, 243, 244,
	245, 246, 247, 248, 250, 249, 437, 316, 287, 283,
	387, 22, 306, 264, 289, 290, 291, 292, 238, 239,
	438, 240, 241, 242, 251, 405, 19, 20, 21, 22,
	17, 307, 312, 306, 85, 86, 211, 87, 88, 89,
	90, 252, 253, 243, 244, 245, 246, 247, 248, 250,
	249, 156, 155, 159, 157, 404, 311, 265, 266, 433,
	316, 431, 316, 238, 239, 388, 240, 241, 242, 251,
	243, 244, 245, 246, 247, 248, 250, 249, 23, 26,
	24, 25, 27, 14, 313, 15, 307, 430, 316, 386,
	238, 239, 385, 240, 241, 242, 251, 429, 316, 428,
	316, 418, 316, 317, 318, 319, 320, 321, 322, 324,
	326, 327, 328, 329, 330, 331, 332, 333, 334, 384,
	336, 338, 417, 316, 383, 22, 213, 72, 73, 374,
	74, 75, 76, 77, 415, 416, 413, 412, 389, 390,
	236, 236, 236, 236, 236, 236, 373, 235, 235, 235,
	235, 235, 235, 67, 370, 67, 369, 236, 363, 364,
	365, 366, 367, 368, 235, 362, 234, 234, 234, 234,
	234, 234, 70, 361, 70, 372, 355, 356, 315, 316,
	313, 288, 17, 234, 190, 432, 78, 79, 80, 81,
	82, 83, 212, 414, 411, 410, 409, 78, 79, 80,
	81, 82, 83, 378, 408, 377, 85, 86, 394, 87,
	88, 89, 90, 156, 155, 159, 157, 85, 86, 393,
	87, 88, 89, 90, 72, 73, 380, 74, 75, 76,
	77, 19, 20, 21, 236, 236, 379, 224, 308, 305,
	304, 235, 235, 303, 302, 301, 300, 299, 298, 236,
	236, 236, 236, 406, 407, 236, 235, 235, 235, 235,
	234, 234, 235, 297, 260, 259, 216, 172, 419, 420,
	421, 422, 153, 236, 426, 234, 234, 234, 234, 352,
	235, 234, 152, 23, 26, 24, 25, 27, 151, 150,
	149, 148, 435, 120, 105, 106, 107, 110, 133, 234,
	93, 95, 92, 91, 96, 108, 109, 112, 111, 113,
	114, 115, 116, 117, 118, 119, 121, 17, 122, 123,
	124, 126, 125, 127, 128, 436, 129, 130, 131, 132,
	22, 145, 146, 147, 427, 84, 136, 134, 135, 140,
	141, 142, 137, 143, 138, 144, 139, 71, 252, 253,
	243, 244, 245, 246, 247, 248, 250, 249, 78, 79,
	80, 81, 82, 83, 424, 423, 401, 400, 103, 104,
	238, 239, 351, 240, 241, 242, 251, 403, 72, 73,
	392, 74, 75, 76, 77, 120, 105, 106, 107, 110,
	133, 391, 341, 95, 97, 98, 339, 108, 109, 112,
	111, 113, 114, 115, 116, 117, 118, 119, 121, 340,
	122, 123, 124, 126, 125, 127, 128, 295, 129, 130,
	131, 132, 347, 346, 269, 268, 267, 263, 136, 134,
	135, 140, 141, 142, 137, 143, 138, 144, 139, 262,
	261, 252, 253, 243, 244, 245, 246, 247, 248, 250,
	249, 28, 293, 399, 69, 16, 4, 358, 154, 10,
	103, 104, 158, 238, 239, 335, 240, 241, 242, 251,
	1, 0, 68, 11, 0, 0, 0, 120, 105, 106,
	107, 110, 133, 0, 0, 95, 97, 98, 337, 108,
	109, 112, 111, 113, 114, 115, 116, 117, 118, 119,
	121, 0, 122, 123, 124, 126, 125, 127, 128, 0,
	129, 130, 131, 132, 0, 0, 0, 0, 0, 0,
	136, 134, 135, 140, 141, 142, 137, 143, 138, 144,
	139, 0, 0, 0, 252, 253, 243, 244, 245, 246,
	247, 248, 250, 249, 214, 217, 218, 219, 220, 221,
	222, 0, 103, 104, 0, 314, 238, 239, 0, 240,
	241, 242, 251, 0, 0, 0, 0, 0, 0, 120,
	105, 106, 107, 110, 133, 0, 0, 95, 97, 98,
	96, 108, 109, 112, 111, 113, 114, 115, 116, 117,
	118, 119, 121, 0, 122, 123, 124, 126, 125, 127,
	128, 0, 129, 130, 131, 132, 0, 0, 0, 0,
	0, 0, 136, 134, 135, 140, 141, 142, 137, 143,
	138, 144, 139, 0, 252, 253, 243, 244, 245, 246,
	247, 248, 250, 249, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 103, 104, 238, 239, 237, 240,
	241, 242, 251, 0, 0, 0, 0, 0, 0, 0,
	0, 120, 105, 106, 107, 110, 133, 0, 0, 95,
	97, 98, 325, 108, 109, 112, 111, 113, 114, 115,
	116, 117, 118, 119, 121, 0, 122, 123, 124, 126,
	125, 127, 128, 0, 129, 130, 131, 132, 0, 0,
	0, 0, 0, 0, 136, 134, 135, 140, 141, 142,
	137, 143, 138, 144, 139, 0, 0, 0, 0, 252,
	253, 243, 244, 245, 246, 247, 248, 250, 249, 0,
	0, 0, 0, 0, 0, 0, 103, 104, 0, 0,
	0, 238, 239, 0, 240, 241, 242, 251, 0, 0,
	0, 0, 0, 120, 105, 106, 107, 110, 133, 0,
	0, 95, 97, 98, 323, 108, 109, 112, 111, 113,
	114, 115, 116, 117, 118, 119, 121, 0, 122, 123,
	124, 126, 125, 127, 128, 0, 129, 130, 131, 132,
	210, 0, 0, 0, 0, 0, 136, 134, 135, 140,
	141, 142, 137, 143, 138, 144, 139, 50, 0, 49,
	0, 57, 207, 51, 52, 54, 55, 56, 59, 58,
	60, 61, 64, 63, 62, 0, 48, 53, 103, 104,
	50, 0, 49, 0, 57, 0, 51, 52, 54, 55,
	56, 59, 58, 60, 61, 64, 63, 62, 0, 0,
	0, 0, 0, 0, 97, 98, 0, 0, 0, 48,
	53, 0, 0, 50, 0, 49, 0, 57, 0, 51,
	52, 54, 55, 56, 59, 58, 60, 61, 64, 63,
	62, 31, 36, 0, 0, 33, 0, 32, 0, 42,
	0, 34, 35, 37, 38, 39, 40, 41, 43, 44,
	45, 46, 47, 31, 36, 0, 0, 33, 0, 32,
	0, 42, 0, 34, 35, 37, 38, 39, 40, 41,
	43, 44, 45, 46, 47, 19, 20, 21, 33, 17,
	32, 310, 42, 0, 34, 35, 37, 38, 39, 40,
	41, 43, 44, 45, 46, 47, 19, 20, 21, 0,
	17, 0, 9, 0, 19, 20, 21, 0, 17, 0,
	169, 0, 0, 0, 0, 0, 0, 0, 0, 274,
	281, 275, 277, 278, 0, 276, 0, 23, 26, 24,
	25, 27, 14, 279, 15, 0, 280, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 23, 26,
	24, 25, 27, 14, 0, 15, 23, 26, 24, 25,
	27, 0, 270, 0, 0, 0, 0, 0, 133, 271,
	0, 272, 0, 0, 22, 0, 273, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 121, 0, 122, 123,
	124, 126, 125, 127, 128, 22, 129, 130, 131, 132,
	65, 3, 0, 22, 0, 0, 136, 134, 135, 140,
	141, 142, 137, 143, 138, 144, 139, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 171, 173, 174, 175, 176, 177, 178, 179,
	180, 181, 182, 183, 184, 185, 186, 187, 188, 120,
	105, 106, 107, 110, 0, 0, 0, 216, 0, 0,
	0, 108, 109, 112, 111, 113, 114, 115, 116, 117,
	118, 119, 120, 105, 106, 107, 110, 0, 0, 0,
	0, 0, 0, 0, 108, 109, 112, 111, 113, 114,
	115, 116, 117, 118, 119,
}

var yyPact = [...]int16{
	1100, -38, -56, 981, -1000, 904, -1000, -1000, -1000, 1100,
	-1000, 434, -1000, 262, 451, 450, -1000, 449, -1000, -1000,
	-1000, -1000, 485, 439, 438, 437, 436, 430, -1000, 420,
	66, 415, 415, 415, 415, 415, 415, 415, 415, 415,
	415, 415, 415, 415, 415, 415, 415, 415, 332, 332,
	332, 332, 332, 332, 332, 332, 332, 332, 332, 332,
	332, 332, 332, 332, 332, 959, 36, 937, 183, 339,
	273, 1255, 414, 414, 414, 414, 414, 414, -1000, -1000,
	-1000, -1000, -1000, -1000, 385, 385, 385, 385, 385, 385,
	385, 725, 1169, -1000, 797, 725, -55, 725, 725, -1000,
	-1000, -1000, -1000, 413, 412, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 596, 595, 583, 169, 582, 581, 580,
	1145, 1102, 124, 112, 122, -1000, -1000, -1000, 328, 725,
	725, 725, 725, 573, -58, 904, -1000, -1000, -1000, -1000,
	411, 396, 395, 394, 393, 392, 391, 388, 387, 1108,
	386, 1002, 1079, -1000, -1000, -1000, -1000, 1002, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 881,
	332, -1000, -1000, -1000, -1000, 881, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 84,
	-1000, -1000, -1000, -1000, 280, -1000, 180, -39, -39, -93,
	-93, -93, -93, -25, 385, -62, -62, -99, -99, -99,
	-99, 702, 325, -1000, -1000, -1000, -1000, -1000, 725, 725,
	725, 725, 725, 909, 817, 725, 725, 725, 725, 725,
	725, 725, 725, 725, 612, 633, 541, -94, -94, 564,
	547, 35, 33, 32, 31, 579, 578, 29, 20, 15,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 519,
	426, 119, 74, 323, -1000, -64, 12, 320, 312, 1169,
	1169, 1169, 1169, 1169, 1169, 467, 937, 90, 301, 23,
	1079, -1000, 180, -59, -1000, -1000, 1169, -94, -94, -101,
	-101, -101, -66, -1000, -66, -1000, -66, -66, -66, -66,
	-66, -66, -101, 146, 146, -1000, -66, -1000, -66, -1000,
	293, 276, -1000, -1000, -1000, -1000, 9, -16, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 573, 1278, -1000, 384,
	374, 87, 58, 271, 266, 239, 236, 156, 212, 285,
	-1000, 84, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 545,
	534, 367, 356, 55, 52, 51, 50, 520, 42, -1000,
	531, 202, 172, 1169, 1169, 352, 344, 343, 342, 283,
	-1000, -1000, 341, 281, -1000, -1000, 269, 248, 1169, 1169,
	1169, 1169, 518, 39, 1169, -1000, 488, -1000, -1000, 246,
	244, 234, 208, -1000, -1000, 333, 206, 138, -1000, -1000,
	-1000, -1000, 1169, -1000, 479, 153, 167, -1000, -1000,
}

var yyPgo = [...]int16{
	0, 630, 4, 622, 3, 19, 2, 1210, 619, 27,
	10, 1, 495, 618, 617, 616, 632, 21, 615, 614,
	6, 24, 5, 26, 7, 0, 18, 613, 8, 612,
	611,
}

var yyR1 = [...]int8{
	0, 1, 1, 1, 1, 1, 1, 7, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
	7, 7, 7, 7, 7, 7, 8, 9, 9, 9,
	9, 9, 9, 9, 9, 9, 2, 3, 4, 26,
	26, 26, 5, 5, 27, 27, 27, 27, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 10, 10, 11,
	12, 12, 12, 12, 12, 12, 15, 15, 16, 16,
	16, 16, 16, 16, 16, 16, 18, 19, 17, 17,
	17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
	17, 17, 20, 20, 20, 20, 20, 13, 13, 13,
	13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
	13, 13, 13, 13, 13, 13, 14, 14, 28, 30,
	29, 29, 21, 21, 21, 21, 21, 21, 21, 21,
	21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
	21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
	21, 21, 21, 22, 22, 22, 22, 22, 22, 22,
	22, 22, 22, 22, 22, 22, 22, 22, 22, 23,
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
	23, 25, 25, 25, 25, 25, 25, 25, 25, 25,
	25, 25, 25, 25, 25, 25, 25, 25, 25, 24,
	24, 24, 24, 24, 24, 24, 24, 24,
}

var yyR2 = [...]int8{
	0, 1, 1, 1, 3, 5, 2, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 1, 3, 1, 1, 1,
	1, 3, 3, 3, 3, 3, 4, 3, 4, 1,
	1, 1, 1, 3, 1, 1, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 1, 2, 3, 3,
	1, 1, 1, 1, 1, 1, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 1, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 1, 1, 1, 1, 2,
	2, 2, 3, 4, 4, 4, 4, 3, 7, 3,
	7, 4, 8, 4, 8, 4, 8, 4, 8, 6,
	10, 4, 8, 4, 6, 10, 4, 4, 3, 4,
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 2, 2, 1, 1, 1,
	1, 4, 4, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 3,
	3, 3, 3, 4, 4, 3, 3, 3,
}

var yyChk = [...]int16{
	-1000, -1, -9, -7, -15, -6, -11, -2, -4, 12,
	-8, -16, -10, -17, 63, 65, -18, 10, -20, 6,
	7, 8, 105, 58, 60, 61, 59, 62, -30, 78,
	81, 82, 88, 86, 92, 93, 83, 94, 95, 96,
	97, 98, 90, 99, 100, 101, 102, 103, 82, 88,
	86, 92, 93, 83, 94, 95, 96, 90, 98, 97,
	99, 100, 103, 102, 101, -7, -9, -6, -16, -19,
	-17, -12, 104, 105, 107, 108, 109, 110, 84, 85,
	86, 87, 88, 89, -12, 104, 105, 107, 108, 109,
	110, 12, 12, 11, -21, 12, 15, 105, 106, -22,
	-23, -24, -25, 79, 80, 5, 6, 7, 16, 17,
	8, 19, 18, 20, 21, 22, 23, 24, 25, 26,
	4, 27, 29, 30, 31, 33, 32, 34, 35, 37,
	38, 39, 40, 9, 48, 49, 47, 53, 55, 57,
	50, 51, 52, 54, 56, 6, 7, 8, 12, 12,
	12, 12, 12, 12, -13, -6, -11, -2, -3, -4,
	67, 68, 69, 70, 72, 71, 73, 74, 75, 12,
	64, -7, 12, -7, -7, -7, -7, -7, -7, -7,
	-7, -7, -7, -7, -7, -7, -7, -7, -7, -6,
	12, -6, -6, -6, -6, -6, -6, -6, -6, -6,
	-6, -6, -6, -6, -6, -6, -6, 13, 13, 81,
	13, 13, 13, 13, -16, -22, 12, -16, -16, -16,
	-16, -16, -16, -17, 12, -17, -17, -17, -17, -17,
	-17, -21, -5, -26, -23, -24, -25, 11, 104, 105,
	107, 108, 109, 84, 85, 86, 87, 88, 89, 91,
	90, 110, 82, 83, -21, 85, 84, -21, -21, 12,
	12, 4, 4, 4, 4, 48, 49, 4, 4, 4,
	27, 34, 36, 41, 27, 29, 33, 30, 31, 41,
	44, 28, 29, 45, 42, 43, 29, 46, 13, -21,
	-21, -21, -21, -29, -28, 4, 81, 12, 12, 12,
	12, 12, 12, 12, 12, 12, -6, -17, 12, -9,
	12, -20, 12, -9, 13, 13, 14, -21, -21, -21,
	-21, -21, -21, 15, -21, 15, -21, -21, -21, -21,
	-21, -21, -21, -21, -21, 13, -21, 15, -21, 15,
	5, 5, 66, 66, 66, 66, 4, 4, 66, 66,
	66, 13, 13, 13, 13, 13, 14, 84, -14, 76,
	77, 13, 13, -26, -26, -26, -26, -26, -26, -10,
	13, 81, -26, 13, 13, 66, 66, -28, -22, 12,
	12, 63, 63, 13, 13, 13, 13, 14, 13, 13,
	14, 6, 6, 12, 12, 63, 63, 63, 63, -27,
	7, 6, 63, 6, 13, 13, -5, -5, 12, 12,
	12, 12, 14, 13, 12, 13, 14, 13, 13, -5,
	-5, -5, -5, 7, 6, 63, -5, 6, 13, 13,
	13, 13, 12, 13, 14, -5, 6, 13, 13,
}

var yyDef = [...]int16{
	0, -2, 1, 2, 3, 27, 28, 29, 30, 0,
	25, 0, 66, 0, 0, 0, 85, 0, 95, 96,
	97, 98, 0, 0, 0, 0, 0, 0, 6, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 27, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 70, 71,
	72, 73, 74, 75, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 67, 0, 0, 0, 0, 0, 157,
	158, 159, 160, 0, 0, 163, 164, 165, 166, 167,
	168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
	178, 179, 180, 181, 182, 183, 184, 185, 186, 187,
	188, 189, 190, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 99, 100, 101, 0, 0,
	0, 0, 0, 0, 4, 31, 32, 33, 34, 35,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 8, 0, 9, 10, 11, 12, 13, 14, 15,
	16, 17, 18, 19, 20, 21, 22, 23, 24, 49,
	0, 50, 51, 52, 53, 54, 55, 56, 57, 58,
	59, 60, 61, 62, 63, 64, 65, 7, 26, 0,
	48, 78, 86, 88, 76, 77, 0, 79, 80, 81,
	82, 83, 84, 69, 0, 89, 90, 91, 92, 93,
	94, 0, 0, 42, 39, 40, 41, 68, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 155, 156, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	191, 192, 193, 194, 195, 196, 197, 198, 199, 200,
	201, 202, 203, 204, 205, 206, 207, 208, 102, 0,
	0, 0, 0, 0, 130, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, -2, 0, 0, 36, 38, 0, 133, 134, 135,
	136, 137, 138, 151, 139, 149, 140, 141, 142, 143,
	144, 145, 146, 147, 148, 132, 150, 153, 152, 154,
	0, 0, 209, 210, 211, 212, 0, 0, 215, 216,
	217, 103, 104, 105, 106, 129, 0, 0, 5, 0,
	0, 107, 109, 0, 0, 0, 0, 0, 0, 0,
	37, 0, 43, 161, 162, 213, 214, 131, 128, 0,
	0, 0, 0, 111, 113, 115, 117, 0, 121, 123,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	44, 45, 0, 0, 126, 127, 0, 0, 0, 0,
	0, 0, 0, 119, 0, 124, 0, 108, 110, 0,
	0, 0, 0, 46, 47, 0, 0, 0, 112, 114,
	116, 118, 0, 122, 0, 0, 0, 120, 125,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
	102, 103, 104, 105, 106, 107, 108, 109, 110,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:126
		{
			l := yylex.(*lexer)
			l.expr = newRootExpr(yyDollar[1].spansetPipeline)
			l.expr.HasVector = l.hasVector
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:127
		{
			l := yylex.(*lexer)
			l.expr = newRootExpr(yyDollar[1].spansetPipelineExpression)
			l.expr.HasVector = l.hasVector
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:128
		{
			l := yylex.(*lexer)
			l.expr = newRootExpr(yyDollar[1].scalarPipelineExpressionFilter)
			l.expr.HasVector = l.hasVector
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:129
		{
			l := yylex.(*lexer)
			l.expr = newRootExprWithMetrics(yyDollar[1].spansetPipeline, yyDollar[3].metricsAggregation)
			l.expr.HasVector = l.hasVector
		}
	case 5:
		yyDollar = yyS[yypt-5 : yypt+1]
//line expr.y:131
		{
			l := yylex.(*lexer)
			l.expr = newRootExprWithMetricsTwoStage(yyDollar[1].spansetPipeline, yyDollar[3].metricsAggregation, yyDollar[5].metricsSecondStage)
			l.expr.HasVector = l.hasVector
		}
	case 6:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:132
		{
			yylex.(*lexer).expr.withHints(yyDollar[2].hints)
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:139
		{
			yyVAL.spansetPipelineExpression = yyDollar[2].spansetPipelineExpression
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:140
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetAnd, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:141
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetChild, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:142
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetParent, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:143
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetDescendant, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:144
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetAncestor, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:145
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetUnion, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:146
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetSibling, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:147
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetNotChild, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:148
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetNotParent, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:149
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetNotDescendant, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:150
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetNotAncestor, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:151
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetNotSibling, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:152
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetUnionChild, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:153
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetUnionParent, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:154
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetUnionDescendant, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:155
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetUnionAncestor, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:156
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetUnionSibling, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:157
		{
			yyVAL.spansetPipelineExpression = yyDollar[1].wrappedSpansetPipeline
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:161
		{
			yyVAL.wrappedSpansetPipeline = yyDollar[2].spansetPipeline
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:164
		{
			yyVAL.spansetPipeline = newPipeline(yyDollar[1].spansetExpression)
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:165
		{
			yyVAL.spansetPipeline = newPipeline(yyDollar[1].scalarFilter)
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:166
		{
			yyVAL.spansetPipeline = newPipeline(yyDollar[1].groupOperation)
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:167
		{
			yyVAL.spansetPipeline = newPipeline(yyDollar[1].selectOperation)
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:168
		{
			yyVAL.spansetPipeline = yyDollar[1].spansetPipeline.addItem(yyDollar[3].spansetExpression)
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:169
		{
			yyVAL.spansetPipeline = yyDollar[1].spansetPipeline.addItem(yyDollar[3].scalarFilter)
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:170
		{
			yyVAL.spansetPipeline = yyDollar[1].spansetPipeline.addItem(yyDollar[3].groupOperation)
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:171
		{
			yyVAL.spansetPipeline = yyDollar[1].spansetPipeline.addItem(yyDollar[3].coalesceOperation)
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:172
		{
			yyVAL.spansetPipeline = yyDollar[1].spansetPipeline.addItem(yyDollar[3].selectOperation)
		}
	case 36:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:176
		{
			yyVAL.groupOperation = newGroupOperation(yyDollar[3].fieldExpression)
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:180
		{
			yyVAL.coalesceOperation = newCoalesceOperation()
		}
	case 38:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:184
		{
			yyVAL.selectOperation = newSelectOperation(yyDollar[3].attributeList)
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:188
		{
			yyVAL.attribute = yyDollar[1].intrinsicField
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:189
		{
			yyVAL.attribute = yyDollar[1].attributeField
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:190
		{
			yyVAL.attribute = yyDollar[1].scopedIntrinsicField
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:194
		{
			yyVAL.attributeList = []Attribute{yyDollar[1].attribute}
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:195
		{
			yyVAL.attributeList = append(yyDollar[1].attributeList, yyDollar[3].attribute)
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:200
		{
			yyVAL.numericList = []float64{yyDollar[1].staticFloat}
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:201
		{
			yyVAL.numericList = []float64{float64(yyDollar[1].staticInt)}
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:202
		{
			yyVAL.numericList = append(yyDollar[1].numericList, yyDollar[3].staticFloat)
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:203
		{
			yyVAL.numericList = append(yyDollar[1].numericList, float64(yyDollar[3].staticInt))
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:207
		{
			yyVAL.spansetExpression = yyDollar[2].spansetExpression
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:208
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetAnd, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:209
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetChild, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:210
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetParent, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:211
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetDescendant, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:212
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetAncestor, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:213
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetUnion, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:214
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetSibling, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:216
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetNotChild, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:217
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetNotParent, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:218
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetNotSibling, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:219
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetNotAncestor, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:220
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetNotDescendant, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:222
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetUnionChild, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:223
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetUnionParent, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:224
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetUnionSibling, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:225
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetUnionAncestor, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:226
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetUnionDescendant, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:228
		{
			yyVAL.spansetExpression = yyDollar[1].spansetFilter
		}
	case 67:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:232
		{
			yyVAL.spansetFilter = newSpansetFilter(NewStaticBool(true))
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:233
		{
			yyVAL.spansetFilter = newSpansetFilter(yyDollar[2].fieldExpression)
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:237
		{
			yyVAL.scalarFilter = newScalarFilter(yyDollar[2].scalarFilterOperation, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:241
		{
			yyVAL.scalarFilterOperation = OpEqual
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:242
		{
			yyVAL.scalarFilterOperation = OpNotEqual
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:243
		{
			yyVAL.scalarFilterOperation = OpLess
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:244
		{
			yyVAL.scalarFilterOperation = OpLessEqual
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:245
		{
			yyVAL.scalarFilterOperation = OpGreater
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:246
		{
			yyVAL.scalarFilterOperation = OpGreaterEqual
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:253
		{
			yyVAL.scalarPipelineExpressionFilter = newScalarFilter(yyDollar[2].scalarFilterOperation, yyDollar[1].scalarPipelineExpression, yyDollar[3].scalarPipelineExpression)
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:254
		{
			yyVAL.scalarPipelineExpressionFilter = newScalarFilter(yyDollar[2].scalarFilterOperation, yyDollar[1].scalarPipelineExpression, yyDollar[3].static)
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:258
		{
			yyVAL.scalarPipelineExpression = yyDollar[2].scalarPipelineExpression
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:259
		{
			yyVAL.scalarPipelineExpression = newScalarOperation(OpAdd, yyDollar[1].scalarPipelineExpression, yyDollar[3].scalarPipelineExpression)
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:260
		{
			yyVAL.scalarPipelineExpression = newScalarOperation(OpSub, yyDollar[1].scalarPipelineExpression, yyDollar[3].scalarPipelineExpression)
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:261
		{
			yyVAL.scalarPipelineExpression = newScalarOperation(OpMult, yyDollar[1].scalarPipelineExpression, yyDollar[3].scalarPipelineExpression)
		}
	case 82:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:262
		{
			yyVAL.scalarPipelineExpression = newScalarOperation(OpDiv, yyDollar[1].scalarPipelineExpression, yyDollar[3].scalarPipelineExpression)
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:263
		{
			yyVAL.scalarPipelineExpression = newScalarOperation(OpMod, yyDollar[1].scalarPipelineExpression, yyDollar[3].scalarPipelineExpression)
		}
	case 84:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:264
		{
			yyVAL.scalarPipelineExpression = newScalarOperation(OpPower, yyDollar[1].scalarPipelineExpression, yyDollar[3].scalarPipelineExpression)
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:265
		{
			yyVAL.scalarPipelineExpression = yyDollar[1].wrappedScalarPipeline
		}
	case 86:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:269
		{
			yyVAL.wrappedScalarPipeline = yyDollar[2].scalarPipeline
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:273
		{
			yyVAL.scalarPipeline = yyDollar[1].spansetPipeline.addItem(yyDollar[3].aggregate)
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:277
		{
			yyVAL.scalarExpression = yyDollar[2].scalarExpression
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:278
		{
			yyVAL.scalarExpression = newScalarOperation(OpAdd, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 90:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:279
		{
			yyVAL.scalarExpression = newScalarOperation(OpSub, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:280
		{
			yyVAL.scalarExpression = newScalarOperation(OpMult, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 92:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:281
		{
			yyVAL.scalarExpression = newScalarOperation(OpDiv, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 93:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:282
		{
			yyVAL.scalarExpression = newScalarOperation(OpMod, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 94:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:283
		{
			yyVAL.scalarExpression = newScalarOperation(OpPower, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 95:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:284
		{
			yyVAL.scalarExpression = yyDollar[1].aggregate
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:285
		{
			yyVAL.scalarExpression = NewStaticInt(yyDollar[1].staticInt)
		}
	case 97:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:286
		{
			yyVAL.scalarExpression = NewStaticFloat(yyDollar[1].staticFloat)
		}
	case 98:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:287
		{
			yyVAL.scalarExpression = NewStaticDuration(yyDollar[1].staticDuration)
		}
	case 99:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:288
		{
			yyVAL.scalarExpression = NewStaticInt(-yyDollar[2].staticInt)
		}
	case 100:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:289
		{
			yyVAL.scalarExpression = NewStaticFloat(-yyDollar[2].staticFloat)
		}
	case 101:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:290
		{
			yyVAL.scalarExpression = NewStaticDuration(-yyDollar[2].staticDuration)
		}
	case 102:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:294
		{
			yyVAL.aggregate = newAggregate(aggregateCount, nil)
		}
	case 103:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:295
		{
			yyVAL.aggregate = newAggregate(aggregateMax, yyDollar[3].fieldExpression)
		}
	case 104:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:296
		{
			yyVAL.aggregate = newAggregate(aggregateMin, yyDollar[3].fieldExpression)
		}
	case 105:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:297
		{
			yyVAL.aggregate = newAggregate(aggregateAvg, yyDollar[3].fieldExpression)
		}
	case 106:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:298
		{
			yyVAL.aggregate = newAggregate(aggregateSum, yyDollar[3].fieldExpression)
		}
	case 107:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:306
		{
			yyVAL.metricsAggregation = newMetricsAggregate(metricsAggregateRate, nil)
		}
	case 108:
		yyDollar = yyS[yypt-7 : yypt+1]
//line expr.y:307
		{
			yyVAL.metricsAggregation = newMetricsAggregate(metricsAggregateRate, yyDollar[6].attributeList)
		}
	case 109:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:308
		{
			yyVAL.metricsAggregation = newMetricsAggregate(metricsAggregateCountOverTime, nil)
		}
	case 110:
		yyDollar = yyS[yypt-7 : yypt+1]
//line expr.y:309
		{
			yyVAL.metricsAggregation = newMetricsAggregate(metricsAggregateCountOverTime, yyDollar[6].attributeList)
		}
	case 111:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:310
		{
			yyVAL.metricsAggregation = newMetricsAggregateWithAttr(metricsAggregateMinOverTime, yyDollar[3].attribute, nil)
		}
	case 112:
		yyDollar = yyS[yypt-8 : yypt+1]
//line expr.y:311
		{
			yyVAL.metricsAggregation = newMetricsAggregateWithAttr(metricsAggregateMinOverTime, yyDollar[3].attribute, yyDollar[7].attributeList)
		}
	case 113:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:312
		{
			yyVAL.metricsAggregation = newMetricsAggregateWithAttr(metricsAggregateMaxOverTime, yyDollar[3].attribute, nil)
		}
	case 114:
		yyDollar = yyS[yypt-8 : yypt+1]
//line expr.y:313
		{
			yyVAL.metricsAggregation = newMetricsAggregateWithAttr(metricsAggregateMaxOverTime, yyDollar[3].attribute, yyDollar[7].attributeList)
		}
	case 115:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:314
		{
			yyVAL.metricsAggregation = newMetricsAggregateWithAttr(metricsAggregateSumOverTime, yyDollar[3].attribute, nil)
		}
	case 116:
		yyDollar = yyS[yypt-8 : yypt+1]
//line expr.y:315
		{
			yyVAL.metricsAggregation = newMetricsAggregateWithAttr(metricsAggregateSumOverTime, yyDollar[3].attribute, yyDollar[7].attributeList)
		}
	case 117:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:316
		{
			yyVAL.metricsAggregation = newAverageOverTimeMetricsAggregator(yyDollar[3].attribute, nil)
		}
	case 118:
		yyDollar = yyS[yypt-8 : yypt+1]
//line expr.y:317
		{
			yyVAL.metricsAggregation = newAverageOverTimeMetricsAggregator(yyDollar[3].attribute, yyDollar[7].attributeList)
		}
	case 119:
		yyDollar = yyS[yypt-6 : yypt+1]
//line expr.y:318
		{
			yyVAL.metricsAggregation = newMetricsAggregateQuantileOverTime(yyDollar[3].attribute, yyDollar[5].numericList, nil)
		}
	case 120:
		yyDollar = yyS[yypt-10 : yypt+1]
//line expr.y:319
		{
			yyVAL.metricsAggregation = newMetricsAggregateQuantileOverTime(yyDollar[3].attribute, yyDollar[5].numericList, yyDollar[9].attributeList)
		}
	case 121:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:320
		{
			yyVAL.metricsAggregation = newMetricsAggregateWithAttr(metricsAggregateHistogramOverTime, yyDollar[3].attribute, nil)
		}
	case 122:
		yyDollar = yyS[yypt-8 : yypt+1]
//line expr.y:321
		{
			yyVAL.metricsAggregation = newMetricsAggregateWithAttr(metricsAggregateHistogramOverTime, yyDollar[3].attribute, yyDollar[7].attributeList)
		}
	case 123:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:322
		{
			yyVAL.metricsAggregation = newMetricsCompare(yyDollar[3].spansetFilter, 10, 0, 0)
		}
	case 124:
		yyDollar = yyS[yypt-6 : yypt+1]
//line expr.y:323
		{
			yyVAL.metricsAggregation = newMetricsCompare(yyDollar[3].spansetFilter, yyDollar[5].staticInt, 0, 0)
		}
	case 125:
		yyDollar = yyS[yypt-10 : yypt+1]
//line expr.y:324
		{
			yyVAL.metricsAggregation = newMetricsCompare(yyDollar[3].spansetFilter, yyDollar[5].staticInt, yyDollar[7].staticInt, yyDollar[9].staticInt)
		}
	case 126:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:331
		{
			yyVAL.metricsSecondStage = newTopKBottomK(OpTopK, yyDollar[3].staticInt)
		}
	case 127:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:332
		{
			yyVAL.metricsSecondStage = newTopKBottomK(OpBottomK, yyDollar[3].staticInt)
		}
	case 128:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:339
		{
			yyVAL.hint = newHint(yyDollar[1].staticStr, yyDollar[3].static)
		}
	case 129:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:343
		{
			yyVAL.hints = newHints(yyDollar[3].hintList)
		}
	case 130:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:347
		{
			yyVAL.hintList = []*Hint{yyDollar[1].hint}
		}
	case 131:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:348
		{
			yyVAL.hintList = append(yyDollar[1].hintList, yyDollar[3].hint)
		}
	case 132:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:356
		{
			yyVAL.fieldExpression = yyDollar[2].fieldExpression
		}
	case 133:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:358
		{
			yyVAL.fieldExpression = newBinaryOperation(OpAdd, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 134:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:359
		{
			yyVAL.fieldExpression = newBinaryOperation(OpSub, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 135:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:360
		{
			yyVAL.fieldExpression = newBinaryOperation(OpMult, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 136:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:361
		{
			yyVAL.fieldExpression = newBinaryOperation(OpDiv, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 137:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:362
		{
			yyVAL.fieldExpression = newBinaryOperation(OpMod, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 138:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:363
		{
			yyVAL.fieldExpression = newBinaryOperation(OpEqual, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 139:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:364
		{
			yyVAL.fieldExpression = newBinaryOperation(OpNotEqual, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 140:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:365
		{
			yyVAL.fieldExpression = newBinaryOperation(OpLess, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 141:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:366
		{
			yyVAL.fieldExpression = newBinaryOperation(OpLessEqual, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 142:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:367
		{
			yyVAL.fieldExpression = newBinaryOperation(OpGreater, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 143:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:368
		{
			yyVAL.fieldExpression = newBinaryOperation(OpGreaterEqual, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 144:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:369
		{
			yyVAL.fieldExpression = newBinaryOperation(OpRegex, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 145:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:370
		{
			yyVAL.fieldExpression = newBinaryOperation(OpNotRegex, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 146:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:371
		{
			yyVAL.fieldExpression = newBinaryOperation(OpPower, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 147:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:372
		{
			yyVAL.fieldExpression = newBinaryOperation(OpAnd, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 148:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:373
		{
			yyVAL.fieldExpression = newBinaryOperation(OpOr, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 149:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:375
		{
			yyVAL.fieldExpression = newUnaryOperation(OpExists, yyDollar[1].fieldExpression)
		}
	case 150:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:376
		{
			yyVAL.fieldExpression = newUnaryOperation(OpExists, yyDollar[3].fieldExpression)
		}
	case 151:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:377
		{
			yyVAL.fieldExpression = newUnaryOperation(OpNotExists, yyDollar[1].fieldExpression)
		}
	case 152:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:378
		{
			yyVAL.fieldExpression = newUnaryOperation(OpNotExists, yyDollar[3].fieldExpression)
		}
	case 153:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:379
		{
			yyVAL.fieldExpression = NewStaticBool(false)
		}
	case 154:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:380
		{
			yyVAL.fieldExpression = NewStaticBool(false)
		}
	case 155:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:382
		{
			yyVAL.fieldExpression = newUnaryOperation(OpSub, yyDollar[2].fieldExpression)
		}
	case 156:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:383
		{
			yyVAL.fieldExpression = newUnaryOperation(OpNot, yyDollar[2].fieldExpression)
		}
	case 157:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:384
		{
			yyVAL.fieldExpression = yyDollar[1].static
		}
	case 158:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:385
		{
			yyVAL.fieldExpression = yyDollar[1].intrinsicField
		}
	case 159:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:386
		{
			yyVAL.fieldExpression = yyDollar[1].attributeField
		}
	case 160:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:387
		{
			yyVAL.fieldExpression = yyDollar[1].scopedIntrinsicField
		}
	case 161:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:388
		{
			yyVAL.fieldExpression = NewStaticBool(true)
			yylex.(*lexer).hasVector = true
		}
	case 162:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:389
		{
			yyVAL.fieldExpression = NewStaticBool(true)
			yylex.(*lexer).hasVector = true
		}
	case 163:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:396
		{
			yyVAL.static = NewStaticString(yyDollar[1].staticStr)
		}
	case 164:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:397
		{
			yyVAL.static = NewStaticInt(yyDollar[1].staticInt)
		}
	case 165:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:398
		{
			yyVAL.static = NewStaticFloat(yyDollar[1].staticFloat)
		}
	case 166:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:399
		{
			yyVAL.static = NewStaticBool(true)
		}
	case 167:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:400
		{
			yyVAL.static = NewStaticBool(false)
		}
	case 168:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:401
		{
			yyVAL.static = NewStaticDuration(yyDollar[1].staticDuration)
		}
	case 169:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:402
		{
			yyVAL.static = NewStaticStatus(StatusOk)
		}
	case 170:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:403
		{
			yyVAL.static = NewStaticStatus(StatusError)
		}
	case 171:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:404
		{
			yyVAL.static = NewStaticStatus(StatusUnset)
		}
	case 172:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:405
		{
			yyVAL.static = NewStaticKind(KindUnspecified)
		}
	case 173:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:406
		{
			yyVAL.static = NewStaticKind(KindInternal)
		}
	case 174:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:407
		{
			yyVAL.static = NewStaticKind(KindServer)
		}
	case 175:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:408
		{
			yyVAL.static = NewStaticKind(KindClient)
		}
	case 176:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:409
		{
			yyVAL.static = NewStaticKind(KindProducer)
		}
	case 177:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:410
		{
			yyVAL.static = NewStaticKind(KindConsumer)
		}
	case 178:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:412
		{
			if yyDollar[1].staticStr == "minInt" {
				yyVAL.static = NewStaticInt(math.MinInt)
			} else if yyDollar[1].staticStr == "maxInt" {
				yyVAL.static = NewStaticInt(math.MaxInt)
			} else {
				yylex.(*lexer).Error("unknown identifier: " + yyDollar[1].staticStr)
				yyVAL.static = NewStaticNil()
			}
		}
	case 179:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:427
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicDuration)
		}
	case 180:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:428
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicName)
		}
	case 181:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:429
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicStatus)
		}
	case 182:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:430
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicStatusMessage)
		}
	case 183:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:431
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicKind)
		}
	case 184:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:432
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicParent)
		}
	case 185:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:433
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicTraceRootSpan)
		}
	case 186:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:434
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicTraceRootService)
		}
	case 187:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:435
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicTraceDuration)
		}
	case 188:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:436
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicNestedSetLeft)
		}
	case 189:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:437
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicNestedSetRight)
		}
	case 190:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:438
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicNestedSetParent)
		}
	case 191:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:443
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicTraceDuration)
		}
	case 192:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:444
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicTraceRootSpan)
		}
	case 193:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:445
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicTraceRootService)
		}
	case 194:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:446
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicTraceID)
		}
	case 195:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:448
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicDuration)
		}
	case 196:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:449
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicName)
		}
	case 197:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:450
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicKind)
		}
	case 198:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:451
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicStatus)
		}
	case 199:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:452
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicStatusMessage)
		}
	case 200:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:453
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicSpanID)
		}
	case 201:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:454
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicParentID)
		}
	case 202:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:455
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicChildCount)
		}
	case 203:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:457
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicEventName)
		}
	case 204:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:458
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicEventTimeSinceStart)
		}
	case 205:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:460
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicLinkTraceID)
		}
	case 206:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:461
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicLinkSpanID)
		}
	case 207:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:463
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicInstrumentationName)
		}
	case 208:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:464
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicInstrumentationVersion)
		}
	case 209:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:468
		{
			yyVAL.attributeField = NewAttribute(yyDollar[2].staticStr)
		}
	case 210:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:469
		{
			yyVAL.attributeField = NewScopedAttribute(AttributeScopeResource, false, yyDollar[2].staticStr)
		}
	case 211:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:470
		{
			yyVAL.attributeField = NewScopedAttribute(AttributeScopeSpan, false, yyDollar[2].staticStr)
		}
	case 212:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:471
		{
			yyVAL.attributeField = NewScopedAttribute(AttributeScopeNone, true, yyDollar[2].staticStr)
		}
	case 213:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:472
		{
			yyVAL.attributeField = NewScopedAttribute(AttributeScopeResource, true, yyDollar[3].staticStr)
		}
	case 214:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:473
		{
			yyVAL.attributeField = NewScopedAttribute(AttributeScopeSpan, true, yyDollar[3].staticStr)
		}
	case 215:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:474
		{
			yyVAL.attributeField = NewScopedAttribute(AttributeScopeEvent, false, yyDollar[2].staticStr)
		}
	case 216:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:475
		{
			yyVAL.attributeField = NewScopedAttribute(AttributeScopeLink, false, yyDollar[2].staticStr)
		}
	case 217:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:476
		{
			yyVAL.attributeField = NewScopedAttribute(AttributeScopeInstrumentation, false, yyDollar[2].staticStr)
		}
	}
	goto yystack /* stack new state and value */
}
